Resources:
  AmplifyRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AmplifyS3AccessRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [amplify.amazonaws.com]
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AccessS3BucketPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - arn:aws:s3:::YOUR_BUCKET_NAME
                  - arn:aws:s3:::YOUR_BUCKET_NAME/*
